PROJECT: Small Library app
addod19/BookStoreLibrary pull request #2
Opened 2020-02-26 16:59 UTC by macnick

In this project we: 
1. Created basic layout using simple HTML and CSS files
2. All the logic is in the JS file
3. JS is organized in a MVC way. **Model** is the Book function constructor. **booklist** object holds all the controller functions and **view** holds the functions that draw the screen
4. There is a button to Add a new Book
5. There is a button to Delete a book
6. There is a button to Toggle the Status of a book between Read/Unread
7. Implemented localStorage to store the books even after the browser closes
8. Implemented messages when the user successfully adds, deletes a book and when validation fails

Please review our code.

2020-02-27 01:37 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome Design!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just one thing to work on............. :slightly_smiling_face: 
 
**_kindly check out my comment below;_**

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-02-27 01:37 UTC, bellom commented on assets/index.js
> +const view = {
Let keep the application logic separated from DOM manipulation tasks.
You move the DOM tasks in another file.
![image](https://user-images.githubusercontent.com/31897434/75403616-812c5c80-5908-11ea-9145-78e898ebc929.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

2020-02-27 09:58 UTC, macnick commented
The you for the review. 

I moved the offending code to the proper place. 

Please review our code.

2020-02-28 00:50 UTC, mcrd25 requested changes
# changes required 👀 🔍 

Hey @macnick! Hey @addod19! 👋 

The project looks fine in the live demo!
But based on changes made, there seems to be an issue when running locally.
See attached screenshot and address these issues! 🙏 
![Screen Shot 2020-02-27 at 8 43 44 PM](https://user-images.githubusercontent.com/31193823/75500016-2f381500-59a2-11ea-939d-ff97f69aa18c.png)

Which causes the project to load like the following:
![Screen Shot 2020-02-27 at 8 48 10 PM](https://user-images.githubusercontent.com/31193823/75500141-7e7e4580-59a2-11ea-82b6-1ea60af8293a.png)


***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-02-28 01:40 UTC, addod19 commented
Bug is fixed. Kindly review our project 🙂

2020-02-28 22:11 UTC, mcrd25 approved these changes
# changes Approved! 💪 🤓 🎊 

Hi Team!

No need for further review! All is well now!

2020-02-28 22:50 UTC, addod19 commented
> # changes Approved! 💪 🤓 🎊
> Hi Team!
> 
> No need for further review! All is well now!

Thank you for your review 👐

2020-02-28 22:52 UTC, merged